name: dart_barcode
description: Port of JsBarcode library
version: 0.0.5
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/lejard-h/dart_barcode

environment:
  sdk: '>=1.13.0 <2.0.0'

dependencies:
  js: ^0.6.0

dev_dependencies:
  browser: ^0.10.0+2
  test: '>=0.12.0 <0.13.0'
